print("What is your name?")
name = input()
print("How old are you?")
age = input()
print("Where are you live?")
city = input()
print("This is {0}.".format(name))
print("It is {0}.".format(age))
print("S(he) live in {0}.".format(city))