print("What is ur name?")
name = input()
print("How old r u?")
age = input()
print("Where r u live?")
city = input()
print("This is {0}.".format(name))
print("It is {0}.".format(age))
print("S(he) live in {0}.".format(city))